<!--TOP MENU cut -->
<ul id="topnav" class="lbut">
{* <li><a href="{$site_domain}">Головна</a> *}
<li><a href="http://iportal.rada.gov.ua">Головна</a>
    <div class="sub left">
    <ul>
        <li><h3><a href="#">Склад і структура</a></h3></li>

        <li><a href="http://w1.c1.rada.gov.ua/pls/site2/p_head_vru">Голова Верховної Ради України</a></li>
        <li><a href="http://w1.c1.rada.gov.ua/pls/site2/p_kerivnyky_vru">Керівництво Верховної Ради України</a></li>
        <li><a href="http://w1.c1.rada.gov.ua/pls/site2/p_deputat_list">Народні депутати України</a></li>
        <li><a href="http://w1.c1.rada.gov.ua/pls/site2/p_fractions">Депутатські фракції</a></li>
        <li><a href="http://w1.c1.rada.gov.ua/pls/site2/p_komitis">Комітети Верховної Ради України</a></li>
        <li><a href="http://w1.c1.rada.gov.ua/pls/site2/p_temp_komitis">Тимчасові комісії</a></li>

        <li><a href="http://w1.c1.rada.gov.ua/pls/site2/p_aparat">Апарат</a></li>
    </ul>
    <ul>
        <li><h3>Архів за скликаннями</h3></li>
        <li><a href="http://static.rada.gov.ua/zakon/new/NEWSAIT/DEPUTAT1/spisok1.htm">1 скликання (1990-1994)</a></li>
        <li><a href="http://w1.c1.rada.gov.ua/pls/radan_gs09/d_index_arh?skl=2">2 скликання (1994-1998)</a></li>
        <li><span>3 скликання (1998-2002)</span> <ul>
            <li><a href="http://w1.c1.rada.gov.ua/pls/radan_gs09/d_index_arh?skl=3">Народні депутати</a></li>
            <li><a href="http://w1.c1.rada.gov.ua/pls/radan_gs09/h_index_arh?nom_skl=3">Хронологія розгляду</a></li>
        </ul></li>
        <li><span>4 скликання (2002-2006)</span> <ul>
            <li><a href="http://w1.c1.rada.gov.ua/pls/site2/p_deputat_list?skl=5">Народні депутати</a></li>
            <li><a href="http://w1.c1.rada.gov.ua/pls/radan_gs09/h_index_arh?nom_skl=4">Хронологія розгляду</a></li>

        </ul></li>
        <li><span>5 скликання (2006-2007)</span> 
        <ul>
            <li><a href="http://w1.c1.rada.gov.ua/pls/site2/p_deputat_list?skl=6">Народні депутати</a></li>
            <li><a href="http://w1.c1.rada.gov.ua/pls/radan_gs09/h_index_arh?nom_skl=5">Хронологія розгляду</a></li>
            <li><a href="{$site_domain}fsview/45949.html">Правова база діяльності</a></li>
        </ul></li>
    </ul>

    <ul>
        <li><h3>Парламентаризм в Україні</h3></li>
        <li><a href="{$site_domain}/documents/parliamentarism/45945.html">Становлення української державності</a></li>
        <li><a href="http://static.rada.gov.ua/NEWSAJT/site/const/index.html">Конституційний процес в Україні</a></li>
        <li><a href="#">Державна символіка</a></li>
    </ul>
    </div>

</li>

<li><a href="#">Законотворчість</a>
  <div class="sub left">
    
    <ul>
      <li><h3>Законопроекти</h3></li>
      <li><a href="http://w1.c1.rada.gov.ua/pls/zweb2/webproc2">Пошук за реквізитами</a></li>
      <li><a href="http://w1.c1.rada.gov.ua/pls/zweb2/webproc555">Зареєстровані за поточний тиждень</a></li>
      <li><a href="http://w1.c1.rada.gov.ua/pls/zweb2/webproc3_current">Знаходяться на розгляді в комітетах</a></li>
      <li><a href="http://w1.c1.rada.gov.ua/pls/site2/p_bills_stand_laws">Прийняті на поточній сесії</a></li>
    </ul>
    <ul>
    
      <li><h3>Пленарні засідання</h3></li>
      
      <li><span>Планування та порядок розгляду питань</span>
        <ul>
         <li><a href="http://static.rada.gov.ua/zakon/new/WR/pd_index.html">Порядок денний сесії</a></li>
         <li><a href="http://static.rada.gov.ua/zakon/new/WR/index.htm">Розклад пленарних засідань</a></li>
         <li><a href="http://static.rada.gov.ua/zakon/new/AWT/index.htm">Порядки денні пленарних засідань</a></li>
         <li><a href="http://static.rada.gov.ua/zakon/new/RK/index.htm">Тижневі графіки засідань комітетів</a></li>
        </ul>
      </li>
      
      <li><span>Розгляд питань порядку денного</span>
       <ul>
        <li><a href="http://w1.c1.rada.gov.ua/pls/radan_gs09/h_index_n">Хронологія розгляду</a></li>
        <li><a href="http://w1.c1.rada.gov.ua/pls/radan_gs09/pd_index_n">Результати розгляду</a></li>
        <li><a href="http://static.rada.gov.ua/zakon/FAXIV/index.htm">Оперативна інформація</a></li>
       </ul>
      </li>
      
      <li><a href="http://static.rada.gov.ua/zakon/new/STENOGR/index.htm">Стенограми пленарних засідань</a></li>
    </ul>
    
    <ul>
      <li><h3>Парламентські слухання</h3></li>
      <li><a href="http://w1.c1.rada.gov.ua/pls/site2/p_par_sl">Проведення парламентських слухань</a></li>
      <li><a href="http://static.rada.gov.ua/zakon/new/par_sl/index.htm">Хроніка парламентських слухань</a></li>
    </ul>
  </div>
 </li>
 
<li><a href="#">Законодавство</a>
    <div class="sub">
    <ul>
        <li><h3>Нормативно-правова база України</h3></li>
        <li><a href="http://zakon2.rada.gov.ua/laws/">Законодавство України</a>
            <ul>
                <li><a href="http://zakon2.rada.gov.ua/laws/main/a#Find">Пошук за реквізитами</a></li>
                <li><a href="http://zakon2.rada.gov.ua/laws/main/nn">Надходження законодавства</a></li>
                <li><a href="http://zakon2.rada.gov.ua/laws/main/a/stru2">Структура бази даних</a></li>
                <li><a href="http://zakon2.rada.gov.ua/laws/main/c">Міжнародні документи</a></li>
                <li><a href="http://zakon2.rada.gov.ua/laws/main/d">Популярні документи</a></li>
                <li><a href="http://zakon2.rada.gov.ua/laws/main/perv">Первинні законодавчі акти</a></li>
                <li><a href="http://zakon2.rada.gov.ua/laws/main/koms">Розподіл за комітетами ВР</a></li>
                <li><a href="http://zakon2.rada.gov.ua/laws/main/annot">Анотації англійською мовою</a></li>
                <li><a href="http://zakon2.rada.gov.ua/laws/main/termin">Термінологія законодавства</a></li>
            </ul>
        </li>
<!--{*        <li><a href="http://zakon2.rada.gov.ua/laws/main/t21">Кодекси України</a> </li>*}-->
  
        <li><a href="http://zakon2.rada.gov.ua/krym">Законодавство АР Крим</a>
            <ul>
                <li><a href="http://zakon2.rada.gov.ua/krym/main/a#Find">Пошук за реквізитами</a></li>
                <li><a href="http://zakon2.rada.gov.ua/krym/main/a/stru2">Структура бази даних</a></li>
            </ul>
        </li>
     </ul>
     <ul>
        <li><h3><a href="http://zakon2.rada.gov.ua/laws/main/pravbase">Правова база діяльності Верховної Ради України</a></h3></li>
        <li><a href="http://zakon2.rada.gov.ua/laws/show/254%EA/96-%E2%F0">Конституція України</a></li>
        <li><a href="http://zakon2.rada.gov.ua/laws/show/1861-17">Закон України "Про Регламент Верховної Ради України"</a></li>
        <li><a href="http://zakon2.rada.gov.ua/laws/show/2790-12">Закон України "Про статус народного депутата України"</a></li>
        <li><a href="http://zakon2.rada.gov.ua/laws/show/116/95-%E2%F0">Закон України "Про комітети Верховної Ради України"</a></li>
        <li><a href="http://zakon2.rada.gov.ua/laws/show/459/00-%F0%E3">Положення про Апарат Верховної Ради України</a></li>   
     
     </ul>
    </div>
  </li>

<li><a href="#">Міжнародна діяльність</a>
    <div class="sub">
     <ul>
<!--        {*<li><h3><a href="#">Міжнародна діяльність</a></h3></li>*}-->
        <li><a href="http://w1.c1.rada.gov.ua/pls/mpz2/organizations.mpo_s">Міжнародні парламентські організації</a></li>
        <li><a href="http://w1.c1.rada.gov.ua/pls/mpz2/parlaments.list">Парламенти зарубіжних країн</a></li>
        <li><a href="http://w1.c1.rada.gov.ua/pls/mpz2/organizations.perm_delegations">Постійні делегації Верховної Ради України</a></li>
        <li><a href="http://w1.c1.rada.gov.ua/pls/mpz2/organizations.dep_groups">Депутатські групи з міжпарламентських зв'язків із зарубіжними країнами</a></li>
        <li><a href="http://w1.c1.rada.gov.ua/pls/mpz2/organizations.asambleas">Міжпарламентські асамблеї</a></li>
        <li><a href="http://w1.c1.rada.gov.ua/pls/mpz2/organizations.inter_commissions">Спільні міжпарламентські комісії</a></li>
        <li><a href="http://pdp.org.ua/">Програма сприяння парламенту України університету Індіани</a></li>
        <li><a href="http://iportal.rada.gov.ua/fsview/46041.html">Вестмінстерська Фундація за демократію</a></li>
    </ul>
  </div>
</li>

<li><a href="#">Інформація</a>
    <div class="sub right">
      <ul>
         <li><h3>Оперативна інформація</h3> </li>
            
      <li><a href="http://w1.c1.rada.gov.ua/pls/zweb2/doclist1?what=1">Укази та розпорядження Президента України</a></li>
      <li><a href="http://w1.c1.rada.gov.ua/pls/zweb2/doclist1?what=0">Постанови та розпорядження Кабінету Міністрів України</a></li>
        
       </ul>
        <ul>
        
        <li><h3>Довідкова інформація</h3> </li>
            
            <li><a href="{$site_domain}/news/Novyny/Derzhavni_zakupivli/">Державні закупівлі</a></li>
            <li><a href="{$site_domain}http://w1.c1.rada.gov.ua/pls/wph/webph_s">Довідник телефонів Верховної Ради України</a></li>
            <li><a href="{$site_domain}/news/Novyny/Parlamentskyj_dovidnyk_znamennykh_i_pamyatnykh_dat">Парламентський довідник знаменних і пам'ятних дат</a></li>
            <li><a href="http://dovidka.com.ua/">Довідник "Офіційна Україна сьогодні"</a></li>
            <li><a href="#">Правила користування веб-сайтом</a></li>
            <li><a href="#">Допомога щодо користування веб-сайтом</a></li>
            
        </ul> 
       <ul>
            <li><h3><a href="{$site_domain}/documents/dostpubinfo">Запити на інформацію</a></h3>
            <li><a href="{$site_domain}/documents/dostpubinfo/45915.html">Документи якими керується Апарат Верховної Ради України у питаннях доступу до публічної інформації</a></li>
            <li><a href="{$site_domain}/documents/dostpubinfo/45916.html">Види інформації, якою володіє Апарат Верховної Ради України</a></li>
    
     <li><span>Доступ до публічної інформації</span>
        <ul>
            <li><a href="http://w1.c1.rada.gov.ua/pls/site2/pkg_public_info.request_form">Електронна форма запиту</a></li>
            <li><a href="#">Паперова форма запиту</a></li>
        </ul>
      </li>        
              
              <li><a href="{$site_domain}/news/Zapyty_na_informatsiyu/Zvity">Звіти</a></li>
          
       </ul>
              
       </div>
    </li> 

<li><a href="#">Контакти</a>
   <div class="sub">
        
    <ul>
        <li><h3><a href="{$site_domain}/feedback">Зворотний зв'язок</a></h3></li>

        <!--<li><a href="{$site_domain}/infocenter">Віртуальна приймальня</a></li>-->
        <li><a href="http://vzvernen.rada.gov.ua/vzvernen/control/uk/index">Відділ з питань звернень громадян</a></li>
        <li><a href="{$site_domain}/news/Poryadok_akredytatsiji,_Polozhennya_pro_ekskursiji">Порядок акредитації, Положення про екскурсії</a></li>
        <!--  <li><a href="">Контактна інформація</a></li>-->
        <li><a href="#">Адреса Верховної Ради України</a></li>
        <!--http://w1.c1.rada.gov.ua/pls/site2/el_main.vr_address-->
    </ul>

    </div>
</li>
<li><a href="#">Ресурси</a>
  <div class="sub right">
    <ul>
        <li><h3>Україна. Адміністративно-територіальний устрій</h3></li>
        
        <li><a href="http://w1.c1.rada.gov.ua/pls/z7503/a002">Статистика</a></li>
        <li><a href="http://w1.c1.rada.gov.ua/pls/z7503/zv.cf1">Пошук за реквізитами</a></li>

        <li><span>Довідники</span>
            <ul>
                <li><a href="http://static.rada.gov.ua/zakon/new/NEWSAIT/ADM/zmist.html">Адміністративно-територіальний устрій</a></li>
                <li><a href="http://static.rada.gov.ua/site/ukr/atuu/dovidnyk/20110617_tel_dovidnyk_rad.pdf">Телефони керівників місцевих рад</a></li>
                <li><a href="http://static.rada.gov.ua/zakon/new/NEWSAIT/ADM/dov/zmist.html">Довідник телефонів та поштових адрес Верховної Ради Автономної Республіки Крим та місцевих рад</a></li>
            </ul>
        </li>
        
        
        <li><span>Нормативно-правові акти з питань адміністративно-територіального устрою України</span>
          <ul>
            <li><a href="http://w1.c1.rada.gov.ua/pls/z7503/A035?rdat=30.06.2004&letter=0">Пошук по областях</a></li>
            <li><a href="http://w1.c1.rada.gov.ua/pls/z7503/a034">Пошук по роках</a></li>
         </ul>
        </li>
        
        <li><span>Місцеві вибори</span>
         <ul>
            <li><a href="http://iportal.rada.gov.ua/fsview/46076.html">Місцеві вибори 2010</a></li>
            <li><a href="http://iportal.rada.gov.ua/fsview/46086.html">Позачергові місцеві вибори</a></li>
         </ul>
        </li>
    </ul>
    <ul>
        <li><h3>Інформаційні ресурси</h3></li>
        <li><a href="http://w1.c1.rada.gov.ua/pls/site2/p_komitis_site">Веб-сайти комітетів Верховної Ради України</a></li>
        <li><a href="http://bilshist.rada.gov.ua/">Сайт парламентської більшості у Верховній Раді України шостого скликання</a></li>
        <li><a href="http://lib.rada.gov.ua/">Бібліотечно-бібліографічні ресурси</a></li>
        <li><a href="{$site_domain}/documents">Електронний архів документів</a></li>
        <li><a href="http://instzak.rada.gov.ua/">Інститут законодавства Верховної Ради України</a></li>
        
        <li> <span>Зовнішні інформаційні ресурси</span>
            <ul>
                 <li><a href="http://www.rada.gov.ua/~dtrp/">Дирекція телерадіопрограм Верховної Ради України (телеканал "РАДА")</a></li>
                 <li><a href="http://www.golos.com.ua/">Газета Верховної Ради "Голос України"</a></li>
                 <li><a href="http://www.viche.info/">Журнал "Віче"</a></li>
                 <li><a href="http://www.nardep.com/">Депутатський клуб "Парламент" та журнал "Народний депутат"</a></li>
            </ul>
          </li>
    </ul>

    <ul>
        <li><h3><a href="#">Веб-сайти органів державної влади України</a></h3></li>
        <li><a href="http://www.president.gov.ua/">Президент України</a></li>
        <li><a href="http://www.kmu.gov.ua/">Кабінет Міністрів України</a></li>
        <li> <span>Судова влада</span>
            <ul>
                <li><a href="http://www.scourt.gov.ua/">Верховний Суд України</a></li>
                <li><a href="http://www.ccu.gov.ua/">Конституційний Суд України</a></li>
                <li><a href="http://www.arbitr.gov.ua/">Вищий господарський суд України</a></li>
            </ul>
        </li>
        <li><a href="http://www.cvk.gov.ua/">Центральна виборча комісія України</a></li>
        <li><a href="http://www.rainbow.gov.ua/">Рада національної безпеки і оборони України</a></li>
        <li><a href="http://www.ombudsman.kiev.ua/">Уповноважений з прав людини</a></li>
        <li><a href="http://www.ac-rada.gov.ua/">Рахункова палата України</a></li>
    </ul>

    </div>
    </li>
    
    <li><a href="#">Новини</a>
    <div class="sub right">
    <ul>
  <li><h3><a href="http://portal.rada.gov.ua/rada/control/uk/publish/category/main_left?cat_id=33440">Оперативні новини</a></h3>
        <ul>
        <li><a href="{$site_domain}/news/Novyny/Povidomlennya">Повідомлення</a></li>
        <li><a href="{$site_domain}/news/Novyny/Anonsy">Анонси</a></li>
        <li><a href="{$site_domain}/news/Novyny/Plenarni_zasidannya">Пленарні засідання</a></li>
        <li><a href="{$site_domain}/news/Novyny/Parlamentski_slukhannya">Парламентські слухання</a></li>
        <li><a href="{$site_domain}/news/Novyny/Dni_Uryadu">Дні Уряду</a></li> 
        </ul>
      </li> 
    </ul> 
  
    <ul>
        <li><h3><a href="#">Огляди ЗМІ</a></h3>
          <ul>
            <li><a href="http://portal.rada.gov.ua/rada/control/uk/archive/docview?typeId=108345">ЗМІ про парламент</a></li>
            <li><a href="http://lib.rada.gov.ua/static/LIBRARY/monitor/degist-region.htm">Огляд регіональної преси</a></li>
            <li><a href="http://lib.rada.gov.ua/static/about/region_pres.html">Архів оглядів регіональної преси</a></li>
          </ul>
        </li>
        <li><a href="{$site_domain}/documents/Parlam_visti">Парламентські вісті</a></li>
    </ul>
    
              <ul> 
          <li><h3>Мультимедіа</h3></li>  
            <li><a href="{$site_domain}/gallery">Фото</a></li>
            <li><a href="{$site_domain}/video">Відео</a></li>
            <li><a href="{$site_domain}/audio">Аудіо</a></li>
<!-- {*          <li><a href="{$site_domain}/tv">Пряма трансляція з залу засідань</a></li> 
            <li><a href="#">Віртуальний тур по Парламенту</a></li>
            <li><a href="#">Презентації</a></li> *}
-->          </ul>

    
    </div>
</ul>
</li>
</ul>


<!-- cut TOP MENU-->