{*TOP MENU cut *}
<ul>




    <li  class="first">


        <a href="#"  class="root">Главная</a>


        <div class="submenu">





            <div class="submenu_col">

                <h3>Состав и структура</h3>




                <ul>

                    
                    <li><a href="http://gapp.rada.gov.ua/radatransl/home/head/1/ru/ ">Председатель Верховной Рады Украины</a></li>

                    <li><a href="http://gapp.rada.gov.ua/radatransl/home/leaders/ru/  ">Руководство Верховной Рады Украины</a></li>

                    <li><a href="http://gapp.rada.gov.ua/radatransl/Home/deps/ru  ">Народные депутаты Украины</a></li>

                    <li><a href="http://gapp.rada.gov.ua/radatransl/Home/Factions/ru ">Депутатские фракции</a></li>

                    <li><a href="http://gapp.rada.gov.ua/radatransl/Home/Committees/ru ">Комитеты Верховной Рады Украины</a></li>

                    <li><a href="http://gapp.rada.gov.ua/radatransl/home/TempCommittees/ru">Временные комиссии</a></li>

                    {*<li><a href="#">Аппарат</a></li>*}
                </ul>





            </div>

            {*      <div class="submenu_col">

                <h3>Архив по созывам</h3>









                <p>5 созыв (2006-2007)</p>
                <ul>

                    <li><a href="http://w1.c1.rada.gov.ua/pls/site/p_deputat_list?skl=6">Народные депутаты</a></li>

                    <li><a href="http://w1.c1.rada.gov.ua/pls/radac_gs09/h_index_arh?nom_skl=5">Хронология рассмотрений</a></li>

                    <li><a href="fsview/45949.html">Правовая база деятельности</a></li>
                </ul>



                <p>4 созыв (2002-2006)</p>
                <ul>

                    <li><a href="http://w1.c1.rada.gov.ua/pls/site/p_deputat_list?skl=5">Народные депутаты</a></li>

                    <li><a href="http://w1.c1.rada.gov.ua/pls/radac_gs09/h_index_arh?nom_skl=4">Хронология рассмотрений</a></li>
                </ul>



                <p>3 созыв (1998-2002)</p>
                <ul>

                    <li><a href="http://w1.c1.rada.gov.ua/pls/radac_gs09/d_index_arh?skl=3">Народные депутаты</a></li>

                    <li><a href="http://w1.c1.rada.gov.ua/pls/radac_gs09/h_index_arh?nom_skl=3">Хронология рассмотрений</a></li>
                </ul>



                <p>2 созыв (1994-1998)</p>
                <ul>

                    <li><a href="http://w1.c1.rada.gov.ua/pls/radac_gs09/d_index_arh?skl=2">Народные депутаты</a></li>
                </ul>



                <p>1 созыв (1990-1994)</p>
                <ul>

                    <li><a href="http://static.rada.gov.ua/zakon/new/NEWSAIT/DEPUTAT1/spisok1.htm">Народные депутаты</a></li>
                </ul>






            </div> *}

            {*      <div class="submenu_col">

                <h3>Парламентаризм в Украине</h3>




                <ul>

                    <li><a href="/documents/parliamentarism/45945.html">Становление украинской государственности</a></li>

                    <li><a href="http://static.rada.gov.ua/NEWSAJT/site/const/index.html">Конституционный процесс в Украине</a></li>

                    <li><a href="#">Государственная символика</a></li>
                </ul>





            </div>






        </div>

        *}


    </li>

    {*
    <li >


        <a href="#"  class="root">Законотворчество</a>


        <div class="submenu">





            <div class="submenu_col">

                <h3>Законопроекти</h3>




                <ul>

                    <li><a href="http://w1.c1.rada.gov.ua/pls/zweb_n/webproc2">Поиск по реквизитам</a></li>

                    <li><a href="http://w1.c1.rada.gov.ua/pls/zweb_n/webproc555">Зарегистрированные на текущей неделе</a></li>

                    <li><a href="http://w1.c1.rada.gov.ua/pls/zweb_n/pkg_zpsended.by_date">Предоставлено народным депутатам</a></li>

                    <li><a href="http://w1.c1.rada.gov.ua/pls/zweb_n/webproc3_current">Находятся на россмотрении в комитетах</a></li>

                    <li><a href="http://w1.c1.rada.gov.ua/pls/site/p_bills_stand_laws">Принятые на текущей сессии</a></li>
                </ul>





            </div>

            <div class="submenu_col">

                <h3>Пленарные заседания</h3>









                <p>Планирование и порядок рассмотрения вопросов</p>
                <ul>

                    <li><a href="http://static.rada.gov.ua/zakon/new/WR/pd_index.html">Повестка дня сессии</a></li>

                    <li><a href="http://static.rada.gov.ua/zakon/new/WR/index.htm">Расписание пленарных заседаний</a></li>

                    <li><a href="/meeting/awt">Повестки дня пленарных заседаний</a></li>

                    <li><a href="http://static.rada.gov.ua/zakon/new/RK/index.htm">Недельные графики заседаний комитетов</a></li>
                </ul>



                <p>Рассмотрение вопросов повестки дня</p>
                <ul>

                    <li><a href="http://w1.c1.rada.gov.ua/pls/radac_gs09/h_index_n">Хронология рассмотрений</a></li>

                    <li><a href="http://w1.c1.rada.gov.ua/pls/radac_gs09/pd_index_n">Результаты рассмотрений</a></li>

                    <li><a href="/meeting/faxiv">Оперативная информация</a></li>

                    <li><a href="/meeting/stenogr">Стенограммы пленарных заседаний</a></li>
                </ul>






            </div>

            <div class="submenu_col">

                <h3>Парламентские слушания</h3>




                <ul>

                    <li><a href="http://w1.c1.rada.gov.ua/pls/site/p_par_sl">Проведение парламентских слушаний</a></li>

                    <li><a href="http://static.rada.gov.ua/zakon/new/par_sl/index.htm">Хроника парламентских слушаний</a></li>
                </ul>





            </div>






        </div>




    </li>
    *}

    {*
    <li >


        <a href="#"  class="root">Законодательство</a>


        <div class="submenu">





            <div class="submenu_col">

                <h3>Нормативно-правовая база Украины</h3>




                <ul>

                    <li><a href="http://zakon.rada.gov.ua/go">Законодательство Украины</a></li>

                    <li><a href="http://zakon.rada.gov.ua/go/a#Find">Поиск по реквизитам</a></li>

                    <li><a href="http://zakon.rada.gov.ua/go/nn">Поступления законодательства</a></li>

                    <li><a href="http://zakon.rada.gov.ua/go/c">Международные документы</a></li>

                    <li><a href="http://zakon.rada.gov.ua/go/d">Популярные документы</a></li>

                    <li><a href="http://zakon.rada.gov.ua/go/perv">Первичные законодательные акты</a></li>

                    <li><a href="http://zakon.rada.gov.ua/go/koms">Разделение по комитетам ВР</a></li>

                    <li><a href="http://zakon.rada.gov.ua/go/annot">Аннотации на английском языке</a></li>

                    <li><a href="http://zakon.rada.gov.ua/krym">Законодательство АР Крым</a></li>

                    <li><a href="http://zakon.rada.gov.ua/krym/main/a#Find">Поиск в законодательстве АР Крым по реквизитам</a></li>

                    <li><a href="http://zakon.rada.gov.ua/krym/main/a/stru2">Структура базы данных законодательства АР Крым</a></li>
                </ul>





            </div>

            <div class="submenu_col">

                <h3>Правовая база деятельности ВР Украины</h3>




                <ul>

                    <li><a href="http://zakon.rada.gov.ua/go/254%D0%BA/96-%D0%B2%D1%80">Конституция Украины</a></li>

                    <li><a href="http://zakon.rada.gov.ua/go/1861-17">Закон "Про Регламент Верховной Рады Украины"</a></li>

                    <li><a href="http://zakon.rada.gov.ua/go/2790-12">Закон "Про статус народного депутата Украины"</a></li>

                    <li><a href="http://zakon.rada.gov.ua/go/116/95-%E2%F0">Закон "Про комитеты Верховной Рады Украины"</a></li>

                    <li><a href="http://zakon.rada.gov.ua/go/459/00-%F0%E3">Положение про Аппарат Верховной Рады Украины</a></li>
                </ul>





            </div>






        </div>




    </li>
    *}
    {*
    <li >


        <a href="#"  class="root">Международная деятельность</a>


        <div class="submenu">


            <div class="submenu_col">
                <ul>
                    <li><a href="http://w1.c1.rada.gov.ua/pls/mpz/organizations.mpo_s">Международные парламентские организации</a></li>
                    <li><a href="http://w1.c1.rada.gov.ua/pls/mpz/parlaments.list">Парламенты зарубежных стран</a></li>
                    <li><a href="http://w1.c1.rada.gov.ua/pls/mpz/organizations.perm_delegations">Постоянные делегации Верховной Рады Украины</a></li>
                    <li><a href="http://w1.c1.rada.gov.ua/pls/mpz/organizations.dep_groups">Депутатские группы по межпарламентским связям с зарубежными странами</a></li>
                    <li><a href="http://w1.c1.rada.gov.ua/pls/mpz/organizations.asambleas">Межпарламентские ассамблеи</a></li>
                    <li><a href="http://w1.c1.rada.gov.ua/pls/mpz/organizations.inter_commissions">Совместные межпарламентские комиссии</a></li>
                    <li><a href="http://pdp.org.ua/">Программа содействия парламенту Украины університета Индианы</a></li>
                    <li><a href="http://iportal.rada.gov.ua/fsview/46041.html">Вестминстерская Фундация за демократию</a></li>
                </ul>
            </div>

        </div>




    </li>

    *}


    <li >
        <a href="#"  class="root">Правовая база деятельности ВР Украины</a>
        <div class="submenu">
            <div class="submenu_col">
                <ul>

                    <li><a href="http://iportal.rada.gov.ua/uploads/documents/29523.pdf">Конституция Украины</a></li>

                    <li><a href="http://iportal.rada.gov.ua/uploads/documents/27398.pdf">Закон "О Регламенте Верховной Рады Украины"</a></li>

                    <li><a href="http://iportal.rada.gov.ua/uploads/documents/27399.pdf">Закон "О статусе народного депутата Украины"</a></li>

                    <li><a href="http://iportal.rada.gov.ua/uploads/documents/27397.pdf">Закон "О комитетах Верховной Рады Украины"</a></li>

                    <li><a href="http://iportal.rada.gov.ua/uploads/documents/27400.pdf">Закон Украины "О временных следственных комиссиях, специальной временной следственной комиссии и временных специальных комиссиях Верховной Рады Украины" </a></li>
					<li><a href="http://zakon.rada.gov.ua/go/ru/pravbase">Всe нормативные документы</a></li>

                </ul>
            </div>
        </div>
    </li>    



    {*

    <li >


        <a href="#"  class="root">Інформация</a>


        <div class="submenu">






            <div class="submenu_col">

                <h3>Справочная информация</h3>




                <ul>

                    <li><a href="/news/Novyny/Derzhavni_zakupivli/">Государственные закупки</a></li>



                    <li><a href="/news/Novyny/Parlamentskyj_dovidnyk_znamennykh_i_pamyatnykh_dat/">Справочник знаменательных и памятных дат ВР Украины</a></li>



                    <li><a href="#">Правила пользования веб-сайтом</a></li>

                    <li><a href="#">Помощь по пользованию веб-сайтом</a></li>
                </ul>





            </div>

            <div class="submenu_col">

                <h3>Запросы на информацию</h3>









                <p>Справки по вопросам доступа к публичной информации</p>
                <ul>

                    <li><a href="/documents/dostpubinfo/45915.html">Документы которыми роководствуется Аппарат ВР Украины в вопросах доступа к публичной информации</a></li>

                    <li><a href="/documents/dostpubinfo/45916.html">Виды информации, которой владеет Аппарат ВР Украины</a></li>

                    <li><a href="/news/Zapyty_na_informatsiyu/Zvity/">Отчеты</a></li>
                </ul>



                <p>Формы доступа к публичной информации</p>
                <ul>

                    <li><a href="http://w1.c1.rada.gov.ua/pls/site/pkg_public_info.request_form">Электронная форма запроса</a></li>

                    <li><a href="#">Форма запроса для предоставления в бумажном виде</a></li>
                </ul>






            </div>






        </div>




    </li>

    *}

    {*
    <li >


        <a href="#"  class="root">Контакти</a>

        <div class="submenu">





            <div class="submenu_col">

                <h3>Обратная связь</h3>


                <ul>

                    <li><a href="feedback">Форма для обратной связи</a></li>

                    <li><a href="/feedback">Адрес Верховной Рады Украины</a></li>
                </ul>



            </div>

            <div class="submenu_col">

                <h3>Запросы граждан</h3>


                <ul>

                    <li><a href="http://vzvernen.rada.gov.ua/vzvernen/control/uk/index">Отдел по вопросам обращения граждан</a></li>

                </ul>



            </div>







        </div>




    </li>
    *}

    <li >


        <a href="#"  class="root">Информационные ресурсы</a>


        <div class="submenu">





            {*     <div class="submenu_col">

                <h3>Украина. Админ.тер.устройство</h3>




                <ul>

                    <li><a href="http://w1.c1.rada.gov.ua/pls/z7502/a002">Статистика</a></li>

                    <li><a href="http://w1.c1.rada.gov.ua/pls/z7502/zv.cf1">Поиск по реквизитам</a></li>
                </ul>

                <p>
                    Справочники
                </p>
                <ul>

                    <li><a href="http://static.rada.gov.ua/zakon/new/NEWSAIT/ADM/zmist.html">Административно-территориальное устройство</a></li>

                    <li><a href="http://static.rada.gov.ua/site/ukr/atuu/dovidnyk/20110617_tel_dovidnyk_rad.pdf">Телефоны руководителей местных советов</a></li>
                    <li><a href="http://static.rada.gov.ua/zakon/new/NEWSAIT/ADM/dov/zmist.html">Справочник телефонрв и почтовых адресов Верховной Рады Автономной Республики Крым и местных советов</a></li>

                </ul>

                <p> Нормативно-правовые акты по вопросам административно-территориального устройства Украины</p>
                <ul>
                    <li><a href="http://w1.c1.rada.gov.ua/pls/z7502/A035?rdat=30.06.2004&letter=0">Поиск по областям</a></li>
                    <li><a href="http://w1.c1.rada.gov.ua/pls/z7502/a034">Поиск по годам</a></li>
                </ul>
                <P>
                    Местные выборы
                </P>
                <ul>
                    <li><a href="http://iportal.rada.gov.ua/fsview/46076.html">Местные выборы 2010</a></li>
                    <li><a href="http://iportal.rada.gov.ua/fsview/46086.html">Внеочередные местные выборы</a></li>
                </ul>

            </div> *}

            <div class="submenu_col">

                <h3><a href="#">Веб-ресурсы ВР Украины</a></h3>
                {*   <P>
                    Информационные ресурсы Верховной Рады Украины
                </P> *}
                <ul>
                    {*<li><a href="http://chairman-lytvyn.rada.gov.ua/">Веб-сайт Председателя Верховной Рады Украины</a></li>*}       
                    <li><a href="http://w1.c1.rada.gov.ua/pls/site2/p_komitis_site">Веб-сайты комитетов Верховной Рады Украины</a></li>
                    {*<li><a href="http://w1.c1.rada.gov.ua/pls/site/p_komitis_site">Веб-сайты комитетов Верховной Рады Украины</a></li>*}
                    {*<li><a href="http://bilshist.rada.gov.ua/">Сайт парламентского большинства в Верховной Раде Украины шестого созыва</a></li>*}
                    <li><a href="http://lib.rada.gov.ua/">Библиотечно-библиографические ресурсы</a></li>
                    {*<li><a href="{$site_domain}/documents">Электронный архив документов</a></li> *}
                    <li><a href="http://instzak.rada.gov.ua/">Институт законодательства Верховной Рады Украины</a></li>
                    <li><a href="http://euinfocentre.rada.gov.ua">Европейский центр информационной поддержки Верховной Рады Украины</a>
                    </li>
                    <li><a href="http://tv.rada.gov.ua/">Дирекция телерадиопрограмм Верховной Рады Украины </a></li>
                </ul>

                <p>
                    Внешние информационные ресурсы
                </p>
                <ul>

                    <li><a href="http://www.golos.com.ua/default.aspx?lang=ru">Газета Верховной Рады "Голос України"</a></li>
                    {*     <li><a href="http://www.viche.info/">Журнал "Віче"</a></li>
                    <li><a href="http://www.nardep.com/">Депутатский клуб "Парламент" и журнал "Народний депутат"</a></li> *}
                </ul>
            </div>

            <div class="submenu_col">

                <h3><a href="#">Веб-сайты органов гос. власти</a></h3>

                <ul>
                    <li><a href="http://www.president.gov.ua/ru/">Президент Украины</a></li>
                </ul>
                <p>
                    Исполнительная власть
                </p>
                <ul>
                    <li><a href="http://www.kmu.gov.ua/control/ru">Кабинет Министров Украины</a></li>
                </ul>

                <P>
                    Судебная власть
                </P>
                <ul>
                    <li><a href="http://www.scourt.gov.ua/">Верховный Суд Украины</a></li>
                    <li><a href="http://www.ccu.gov.ua/ru">Конституционный Суд Украины</a></li>
                    <li><a href="http://www.arbitr.gov.ua/">Высший хозяйственный суд Украины</a></li>
                </ul>
                <P>
                    Другие государственные органы
                </P>
                <ul>
                    <li><a href="http://www.cvk.gov.ua/">Центральная избирательная комиссия Украины</a></li>
                    <li><a href="http://www.rainbow.gov.ua/">Совет национальной безопасности и обороны Украины</a></li>
                    <li><a href="http://www.ombudsman.gov.ua/">Уполномоченный по правам человека</a></li>
                    <li><a href="http://www.ac-rada.gov.ua/control/main/ru/index">Счетная палата Украины</a></li>
                </ul>

            </div>




    </li>


    <li  class="last">


        <a href="#"  class="root">Новости</a>


        <div class="submenu">





            <div class="submenu_col">

                <h3><a href="#">Оперативные новости</a></h3>




                <ul>

                    <li><a href="/ru/news/Novosty/Soobshchenyya/">Сообщения  </a></li>

                    <li><a href="/ru/preview/anonsy_sobytij/">Анонсы событий</a></li>

                    {*        <li><a href="/news/Novyny/Plenarni_zasidannya/">Пленарные заседания</a></li>

                    <li><a href="/news/Novyny/Parlamentski_slukhannya/">Парламентские слушания</a></li>

                    <li><a href="/news/Novyny/Dni_Uryadu/">Дни Правительства</a></li> *}
                </ul>





            </div>


            {*    
            <div class="submenu_col">

                <h3>Обзоры СМИ</h3>




                <ul>

                    <li><a href="http://portal.rada.gov.ua/rada/control/uk/archive/docview?typeId=108345">СМИ про парламент</a></li>

                    <li><a href="http://lib.rada.gov.ua/static/LIBRARY/monitor/degist-region.htm">Обзор региональной прессы</a></li>

                    <li><a href="http://iportal.rada.gov.ua/documents/Oglad_reg_ZMIvf/49243.html">Архив обзоров региональной прессы</a></li>

                    <li><a href="/documents/Parlam_visti/">Парламентские вести</a></li>
                </ul>





            </div>
            *}

            <div class="submenu_col">

                <h3>Мультимедиа</h3>




                <ul>

                    <li><a href="/gallery/">Фото</a></li>

                    <li><a href="/video/">Видео</a></li>

                    <li><a href="/audio/">Аудио</a></li>
                </ul>





            </div>






        </div>




    </li>
</ul>
{* cut TOP MENU*}
