<!--TOP MENU cut -->
<ul>




    <li  class="first">


	<a href="#"  class="root">Головна</a>            


	<div class="submenu">





	    <div class="submenu_col">

		<h3>Слад і структура</h3>




		<ul>

		    <li><a href="http://w1.c1.rada.gov.ua/pls/site/p_head_vru">Голова Верховної Ради України</a></li>

		    <li><a href="http://w1.c1.rada.gov.ua/pls/site/p_kerivnyky_vru">Керівництво Верховної Ради України</a></li>

		    <li><a href="http://w1.c1.rada.gov.ua/pls/site/p_deputat_list">Народні депутати України</a></li>

		    <li><a href="http://w1.c1.rada.gov.ua/pls/site/p_fractions">Депутатські фракції</a></li>

		    <li><a href="http://w1.c1.rada.gov.ua/pls/site/p_komitis">Комітети Верховної Ради України</a></li>

		    <li><a href="http://w1.c1.rada.gov.ua/pls/site/p_temp_komitis">Тимчасові комісії</a></li>

		    <li><a href="http://w1.c1.rada.gov.ua/pls/site/p_aparat">Апарат</a></li>
		</ul>





	    </div>

	    <div class="submenu_col">

		<h3>Архів за скликаннями</h3>









		<p>5 скликання (2006-2007)</p>                                            
		<ul>

		    <li><a href="http://w1.c1.rada.gov.ua/pls/site/p_deputat_list?skl=6">Народні депутати</a></li>

		    <li><a href="http://w1.c1.rada.gov.ua/pls/radac_gs09/h_index_arh?nom_skl=5">Хронологія розгляду</a></li>

		    <li><a href="fsview/45949.html">Правова база діяльності</a></li>
		</ul>



		<p>4 скликання (2002-2006)</p>                                            
		<ul>

		    <li><a href="http://w1.c1.rada.gov.ua/pls/site/p_deputat_list?skl=5">Народні депутати</a></li>

		    <li><a href="http://w1.c1.rada.gov.ua/pls/radac_gs09/h_index_arh?nom_skl=4">Хронологія розгляду</a></li>
		</ul>



		<p>3 скликання (1998-2002)</p>                                            
		<ul>

		    <li><a href="http://w1.c1.rada.gov.ua/pls/radac_gs09/d_index_arh?skl=3">Народні депутати</a></li>

		    <li><a href="http://w1.c1.rada.gov.ua/pls/radac_gs09/h_index_arh?nom_skl=3">Хронологія розгляду</a></li>
		</ul>



		<p>2 скликання (1994-1998)</p>                                            
		<ul>

		    <li><a href="http://w1.c1.rada.gov.ua/pls/radac_gs09/d_index_arh?skl=2">Народні депутати</a></li>
		</ul>



		<p>1 скликання (1990-1994)</p>                                            
		<ul>

		    <li><a href="http://static.rada.gov.ua/zakon/new/NEWSAIT/DEPUTAT1/spisok1.htm">Народні депутати</a></li>
		</ul>






	    </div>

	    <div class="submenu_col">

		<h3>Парламентаризм в Україні</h3>




		<ul>

		    <li><a href="/documents/parliamentarism/45945.html">Становлення української державності</a></li>

		    <li><a href="http://static.rada.gov.ua/NEWSAJT/site/const/index.html">Конституційний процес в Україні</a></li>

		    <li><a href="#">Державна символіка</a></li>
		</ul>





	    </div>






	</div>




    </li>


    <li >


	<a href="#"  class="root">Законотворчість</a>            


	<div class="submenu">





	    <div class="submenu_col">

		<h3>Законопроекти</h3>




		<ul>

		    <li><a href="http://w1.c1.rada.gov.ua/pls/zweb_n/webproc2">Пошук за реквізитами</a></li>

		    <li><a href="http://w1.c1.rada.gov.ua/pls/zweb_n/webproc555">Зареєстровані за поточний тиждень</a></li>

		    <li><a href="http://w1.c1.rada.gov.ua/pls/zweb_n/pkg_zpsended.by_date">Надано народним депутатам</a></li>

		    <li><a href="http://w1.c1.rada.gov.ua/pls/zweb_n/webproc3_current">Знаходяться на розгляді в комітетах</a></li>

		    <li><a href="http://w1.c1.rada.gov.ua/pls/site/p_bills_stand_laws">Прийняті на поточній сесії</a></li>
		</ul>





	    </div>

	    <div class="submenu_col">

		<h3>Пленарні засідання</h3>









		<p>Планування та порядок розгляду питань</p>                                            
		<ul>

		    <li><a href="http://static.rada.gov.ua/zakon/new/WR/pd_index.html">Порядок денний сесії</a></li>

		    <li><a href="http://static.rada.gov.ua/zakon/new/WR/index.htm">Розклад пленарних засідань</a></li>

		    <li><a href="/meeting/awt">Порядки денні пленарних засідань</a></li>

		    <li><a href="http://static.rada.gov.ua/zakon/new/RK/index.htm">Тижневі графіки засідань комітетів</a></li>
		</ul>



		<p>Розгляд питань порядку денного</p>                                            
		<ul>

		    <li><a href="http://w1.c1.rada.gov.ua/pls/radac_gs09/h_index_n">Хронологія розгляду</a></li>

		    <li><a href="http://w1.c1.rada.gov.ua/pls/radac_gs09/pd_index_n">Результати розгляду</a></li>

		    <li><a href="/meeting/faxiv">Оперативна інформація</a></li>

		    <li><a href="/meeting/stenogr">Стенограми пленарних засідань</a></li>
		</ul>






	    </div>

	    <div class="submenu_col">

		<h3>Парламентські слухання</h3>




		<ul>

		    <li><a href="http://w1.c1.rada.gov.ua/pls/site/p_par_sl">Проведення парламентських слухань</a></li>

		    <li><a href="http://static.rada.gov.ua/zakon/new/par_sl/index.htm">Хроніка парламентських слухань</a></li>
		</ul>





	    </div>






	</div>




    </li>


    <li >


	<a href="#"  class="root">Законодавство</a>            


	<div class="submenu">





	    <div class="submenu_col">

		<h3>Нормативно-правова база України</h3>




		<ul>

		    <li><a href="http://zakon.rada.gov.ua/go">Законодавство України</a></li>

		    <li><a href="http://zakon.rada.gov.ua/go/a#Find">Пошук за реквізитами</a></li>

		    <li><a href="http://zakon.rada.gov.ua/go/nn">Надходження законодавства</a></li>

		    <li><a href="http://zakon.rada.gov.ua/go/c">Міжнародні документи</a></li>

		    <li><a href="http://zakon.rada.gov.ua/go/d">Популярні документи</a></li>

		    <li><a href="http://zakon.rada.gov.ua/go/perv">Первинні законодавчі акти</a></li>

		    <li><a href="http://zakon.rada.gov.ua/go/koms">Розподіл за комітетами ВР</a></li>

		    <li><a href="http://zakon.rada.gov.ua/go/annot">Анотації англійською мовою</a></li>

		    <li><a href="http://zakon.rada.gov.ua/krym">Законодавство АР Крим</a></li>

		    <li><a href="http://zakon.rada.gov.ua/krym/main/a#Find">Пошук законодавство АР Крим за реквізитами</a></li>

		    <li><a href="http://zakon.rada.gov.ua/krym/main/a/stru2">Структура бази даних законодавства АР Крим</a></li>
		</ul>





	    </div>

	    <div class="submenu_col">

		<h3>Правова база діяльності ВР України</h3>




		<ul>

		    <li><a href="http://zakon.rada.gov.ua/go/254%D0%BA/96-%D0%B2%D1%80">Конституція України</a></li>

		    <li><a href="http://zakon.rada.gov.ua/go/1861-17">Закон "Про Регламент Верховної Ради України"</a></li>

		    <li><a href="http://zakon.rada.gov.ua/go/2790-12">Закон "Про статус народного депутата України</a></li>

		    <li><a href="http://zakon.rada.gov.ua/go/116/95-%E2%F0">Закон "Про комітети Верховної Ради України</a></li>

		    <li><a href="http://zakon.rada.gov.ua/go/459/00-%F0%E3">Положення про Апарат Верховної Ради України</a></li>
		</ul>





	    </div>






	</div>




    </li>


    <li >


	<a href="#"  class="root">Міжнародна діяльність</a>            


	<div class="submenu">


	    <div class="submenu_col">
		<ul>
		    <li><a href="http://w1.c1.rada.gov.ua/pls/mpz/organizations.mpo_s">Міжнародні парламентські організації</a></li>
		    <li><a href="http://w1.c1.rada.gov.ua/pls/mpz/parlaments.list">Парламенти зарубіжних країн</a></li>
		    <li><a href="http://w1.c1.rada.gov.ua/pls/mpz/organizations.perm_delegations">Постійні делегації Верховної Ради України</a></li>
		    <li><a href="http://w1.c1.rada.gov.ua/pls/mpz/organizations.dep_groups">Депутатські групи з міжпарламентських зв'язків із зарубіжними країнами</a></li>
		    <li><a href="http://w1.c1.rada.gov.ua/pls/mpz/organizations.asambleas">Міжпарламентські асамблеї</a></li>
		    <li><a href="http://w1.c1.rada.gov.ua/pls/mpz/organizations.inter_commissions">Спільні міжпарламентські комісії</a></li>
		    <li><a href="http://pdp.org.ua/">Програма сприяння парламенту України університету Індіани</a></li>
		    <li><a href="http://iportal.rada.gov.ua/fsview/46041.html">Вестмінстерська Фундація за демократію</a></li>
		</ul>       
	    </div>

	</div>




    </li>


    <li >


	<a href="#"  class="root">Інформація</a>            


	<div class="submenu">






	    <div class="submenu_col">

		<h3>Довідкова інформація</h3>




		<ul>

		    <li><a href="/news/Novyny/Derzhavni_zakupivli/">Державні закупівлі</a></li>

		    

		    <li><a href="/news/Novyny/Parlamentskyj_dovidnyk_znamennykh_i_pamyatnykh_dat/">Довідник знаменних і пам'ятних дат ВР України</a></li>

		    

		    <li><a href="#">Правила користування веб-сайтом</a></li>

		    <li><a href="#">Допомога щодо користування веб-сайтом</a></li>
		</ul>





	    </div>

	    <div class="submenu_col">

		<h3>Запити на інформацію</h3>









		<p>Доівдки з питань доступу до публічної інформації</p>                                            
		<ul>

		    <li><a href="/documents/dostpubinfo/45915.html">Документи якими керується Апарат ВР України у питаннях доступу до публічної інформації</a></li>

		    <li><a href="/documents/dostpubinfo/45916.html">Види інформації, якою володіє Апарат ВР України</a></li>

		    <li><a href="/news/Zapyty_na_informatsiyu/Zvity/">Звіти</a></li>
		</ul>



		<p>Форми доступу до публічної інформації</p>                                            
		<ul>

		    <li><a href="http://w1.c1.rada.gov.ua/pls/site/pkg_public_info.request_form">Електронна форма запиту</a></li>

		    <li><a href="#">Паперова форма запиту</a></li>
		</ul>






	    </div>






	</div>




    </li>


    <li >


	<a href="#"  class="root">Контакти</a>            

	<div class="submenu">





	    <div class="submenu_col">

		<h3>Зворотний зв'язок</h3>


		<ul>

		    <li><a href="feedback">Форма зворотнього зв'язку</a></li>

		    <li><a href="/feedback">Адреса Верховної Ради України</a></li>
		</ul>



	    </div>
	    
	    <div class="submenu_col">

		<h3>Запити громадян</h3>


		<ul>

		    <li><a href="http://vzvernen.rada.gov.ua/vzvernen/control/uk/index">Відділ з питань звернень громадян</a></li>

		</ul>



	    </div>
	    
	    
	    
	    

	    

	</div>




    </li>


    <li >


	<a href="#"  class="root">Ресурси</a>            


	<div class="submenu">





	    <div class="submenu_col">

		<h3>Україна. Адмін.тер.устрій</h3>




		<ul>

		    <li><a href="http://w1.c1.rada.gov.ua/pls/z7502/a002">Статистика</a></li>

		    <li><a href="http://w1.c1.rada.gov.ua/pls/z7502/zv.cf1">Пошук за реквізитами</a></li>
		</ul>
		
		<p>
		    Довідники
		</p>
		<ul>

		    <li><a href="http://static.rada.gov.ua/zakon/new/NEWSAIT/ADM/zmist.html">Адміністративно-територіальний устрій</a></li>

		    <li><a href="http://static.rada.gov.ua/site/ukr/atuu/dovidnyk/20110617_tel_dovidnyk_rad.pdf">Телефони керівників місцевих рад</a></li>
		<li><a href="http://static.rada.gov.ua/zakon/new/NEWSAIT/ADM/dov/zmist.html">Довідник телефонів та поштових адрес Верховної Ради Автономної Республіки Крим та місцевих рад</a></li>
		
		</ul>
		
		<p> Нормативно-правові акти з питань адміністративно-територіального устрою України</p>
		<ul>
            <li><a href="http://w1.c1.rada.gov.ua/pls/z7502/A035?rdat=30.06.2004&letter=0">Пошук по областях</a></li>
            <li><a href="http://w1.c1.rada.gov.ua/pls/z7502/a034">Пошук по роках</a></li>
         </ul>
		<P>
		    Місцеві вибори
		</P>
<ul>
            <li><a href="http://iportal.rada.gov.ua/fsview/46076.html">Місцеві вибори 2010</a></li>
            <li><a href="http://iportal.rada.gov.ua/fsview/46086.html">Позачергові місцеві вибори</a></li>
		</ul>

	    </div>
	    
	    <div class="submenu_col">

		<h3><a href="#">Інформаційні ресурси</a></h3>
		<P>
		    Інформаційні ресурси Верховної Ради України
		</P>
		<ul>
		           <li><a href="http://w1.c1.rada.gov.ua/pls/site/p_komitis_site">Веб-сайти комітетів Верховної Ради України</a></li>
        <li><a href="http://bilshist.rada.gov.ua/">Сайт парламентської більшості у Верховній Раді України шостого скликання</a></li>
        <li><a href="http://lib.rada.gov.ua/">Бібліотечно-бібліографічні ресурси</a></li>
        <li><a href="{$site_domain}/documents">Електронний архів документів</a></li>
        <li><a href="http://instzak.rada.gov.ua/">Інститут законодавства Верховної Ради України</a></li>
	<li><a href="http://euinfocentre.rada.gov.ua">Європейський центр інформаційної підтримки Верховної Ради України</a>
	</li>
	<li><a href="http://www.rada.gov.ua/~dtrp/">Дирекція телерадіопрограм Верховної Ради України </a></li>
		</ul>
		
		<p>
		    Зовнішні інформаційні ресурси
		</p>
	    <ul>
                 
                 <li><a href="http://www.golos.com.ua/">Газета Верховної Ради "Голос України"</a></li>
                 <li><a href="http://www.viche.info/">Журнал "Віче"</a></li>
                 <li><a href="http://www.nardep.com/">Депутатський клуб "Парламент" та журнал "Народний депутат"</a></li>
            </ul>
	    </div>
		
		<div class="submenu_col">

		<h3><a href="#">Веб-сайти органів держ. влади</a></h3>
		
		<ul>
		    <li><a href="http://www.president.gov.ua/">Президент України</a></li>
		  </ul>
		<p>
			Виконавча влада
		    </p>
		    <ul>   
		    <li><a href="http://www.kmu.gov.ua/">Кабінет Міністрів України</a></li>
		    </ul>
		
		<P>
		    Судова влада
		</P>
	    <ul>
                <li><a href="http://www.scourt.gov.ua/">Верховний Суд України</a></li>
                <li><a href="http://www.ccu.gov.ua/">Конституційний Суд України</a></li>
                <li><a href="http://www.arbitr.gov.ua/">Вищий господарський суд України</a></li>
            </ul>
	    <P>
		    Інші державні органи
		</P>
	    <ul>
                <li><a href="http://www.cvk.gov.ua/">Центральна виборча комісія України</a></li>
        <li><a href="http://www.rainbow.gov.ua/">Рада національної безпеки і оборони України</a></li>
        <li><a href="http://www.ombudsman.kiev.ua/">Уповноважений з прав людини</a></li>
        <li><a href="http://www.ac-rada.gov.ua/">Рахункова палата України</a></li>
            </ul>
	    
	    </div>




    </li>


    <li  class="last">


	<a href="#"  class="root">Новини</a>            


	<div class="submenu">





	    <div class="submenu_col">

		<h3><a href="#">Оперативні новини</a></h3>




		<ul>

		    <li><a href="/news/Novyny/Povidomlennya/">Повідомлення  </a></li>

		    <li><a href="/preview/Anonsy_podij/">Анонси подій</a></li>

		    <li><a href="/news/Novyny/Plenarni_zasidannya/">Пленарні засідання</a></li>

		    <li><a href="/news/Novyny/Parlamentski_slukhannya/">Парламентські слухання</a></li>

		    <li><a href="/news/Novyny/Dni_Uryadu/">Дні Уряду</a></li>
		</ul>





	    </div>

	    <div class="submenu_col">

		<h3>Огляди ЗМІ</h3>




		<ul>

		    <li><a href="http://portal.rada.gov.ua/rada/control/uk/archive/docview?typeId=108345">ЗМІ про парламент</a></li>

		    <li><a href="http://lib.rada.gov.ua/static/LIBRARY/monitor/degist-region.htm">Огляд регіональної преси</a></li>

		    <li><a href="http://iportal.rada.gov.ua/documents/Oglad_reg_ZMIvf/49243.html">Архів оглядів регіональної преси</a></li>

		    <li><a href="/documents/Parlam_visti/">Парламентські вісті</a></li>
		</ul>





	    </div>

	    <div class="submenu_col">

		<h3>Мультимедіа</h3>




		<ul>

		    <li><a href="/gallery/">Фото</a></li>

		    <li><a href="/video/">Відео</a></li>

		    <li><a href="/audio/">Аудіо</a></li>
		</ul>





	    </div>






	</div>




    </li>
</ul>
<!-- cut TOP MENU--> 