<!-- TOP MENU cut -->
<ul>    


    <li  class="first">


    <a href="#"  class="root">Main page</a>            


    <div class="submenu">     


        <div class="submenu_col">

        <h3>Personnel and Structure of The Verkhovna Rada of Ukraine</h3>

        
        <ul>

            <li><a href="http://gapp.rada.gov.ua/radatransl/home/head/1/en/ ">The Chairperson of The Verkhovna Rada of Ukraine</a></li>

            <li><a href="http://gapp.rada.gov.ua/radatransl/home/leaders/en/ ">The Leaders of The Verkhovna Rada of Ukraine</a></li>
            

            <li><a href="http://gapp.rada.gov.ua/radatransl/Home/deps/en ">The People's Deputies of Ukraine</a></li>
                    {*<li><a href="#">The People's Deputies of Ukraine</a></li>*}

            <li><a href="http://gapp.rada.gov.ua/radatransl/Home/Factions/en ">Deputy Factions</a></li>

            <li><a href="http://gapp.rada.gov.ua/radatransl/Home/Committees/en ">The Committees of The Verkhovna Rada of Ukraine</a></li>

            <li><a href="http://gapp.rada.gov.ua/radatransl/home/TempCommittees/en">Ad Hoc and Interim Panels of The Verkhovna Rada of Ukraine</a></li>

        <!--    <li><a href="http://static.rada.gov.ua/site/eng2/secretariate.htm">The Verkhovna Rada of Ukraine Secretariate</a></li>
             <li><a href="#">Reference Information</a></li>
           <li><a href="http://static.rada.gov.ua/site/eng/dovidkova_info_address.html">Reference Information</a></li>-->
        </ul>       


        </div>


        <!--<div class="submenu_col"> 

        <h3>Parliamentarism in Ukraine</h3>  

        <ul>

            <li><a href="#">Establishment of Ukrainian Statehood</a></li>
            <!--<li><a href="http://static.rada.gov.ua/site/postanova_eng/Est_Ukr_State.htm">Establishment of Ukrainian Statehood</a></li>

            <li><a href="http://static.rada.gov.ua/site/const_eng/constitution_eng.htm">Constitutional Process in Ukraine</a></li>   
             
        </ul> 
        
        </div>-->
         <div class="submenu_col">

         <h3>Web-Pages of State Authority Supreme Bodies</h3>   

        <ul>

            <li><a href="http://www.president.gov.ua/en/">The President of Ukraine</a></li>

            <li><a href="http://www.kmu.gov.ua/control/en">The Cabinet of Ministers of Ukraine</a></li>

            <li><a href="http://www.scourt.gov.ua/">The Supreme Court of Ukraine</a></li>             

            <li><a href="http://www.ombudsman.gov.ua/en/">Ombudsman</a></li>             

             
        </ul>
         </div>    


    </li>


    <li >


      <a href="#" class="root_r">Legislative Activities</a> 
      <!--<a href="http://static.rada.gov.ua/site/eng_zp/eng_zp_rubric.html" class="root_r">Legislative Activities</a>--> 
        
    </li>   
    <li >      

      <a href="http://zakon.rada.gov.ua/laws/main/en/annot"class="root_r">Laws of Ukraine</a> 
        
    </li>      
              
            

   <!-- <li >


    <a href="#"  class="root">International Activities</a>            


    <div class="submenu">


        <div class="submenu_col">
        <ul>
            <li><a href="#">International Parliamentary Organizations</a></li>
            <li><a href="http://static.rada.gov.ua/site/eng/inter_parliamentary/inter_parliamentary_organizations.html">International Parliamentary Organizations</a></li>
            <li><a href="#">Standing Delegations of The Verkhovna Rada of Ukraine</a></li> 
            <li><a href="http://static.rada.gov.ua/site/eng/inter_parliamentary/standing_delegations.html">Standing Delegations of The Verkhovna Rada of Ukraine</a></li>  
            <li><a href="#">Inter-Parliamentary Assemblies</a></li>
            <li><a href="http://static.rada.gov.ua/site/eng/inter_parliamentary/interparliamentary_assemblies.html">Inter-Parliamentary Assemblies</a></li> 
            <li><a href="#">Joint Inter-Parliamentary Commissions</a></li>
            <li><a href="http://static.rada.gov.ua/site/eng/inter_parliamentary/joint_interparliamentary_commissions.html">Joint Inter-Parliamentary Commissions</a></li> 
            <li><a href="#">Parliamentary Development Project for Ukraine Indiana University</a></li>
            <li><a href="http://www.iupdp.org/">Parliamentary Development Project for Ukraine Indiana University</a></li>-->
        
          <!-- <li><a href="http://w1.c1.rada.gov.ua/pls/mpz/parlaments.list">Парламенти зарубіжних країн</a></li>
            <li><a href="http://w1.c1.rada.gov.ua/pls/mpz/organizations.perm_delegations">Постійні делегації Верховної Ради України</a></li>
            <li><a href="http://w1.c1.rada.gov.ua/pls/mpz/organizations.dep_groups">Депутатські групи з міжпарламентських зв'язків із зарубіжними країнами</a></li>
            <li><a href="http://w1.c1.rada.gov.ua/pls/mpz/organizations.asambleas">Міжпарламентські асамблеї</a></li>
            <li><a href="http://w1.c1.rada.gov.ua/pls/mpz/organizations.inter_commissions">Спільні міжпарламентські комісії</a></li>
            <li><a href="http://pdp.org.ua/">Програма сприяння парламенту України університету Індіани</a></li>
            <li><a href="http://iportal.rada.gov.ua/fsview/46041.html">Вестмінстерська Фундація за демократію</a></li>   
        </ul>       
        </div>

    </div>  

    </li>-->
    
    <li >   

      <a href="http://iportal.rada.gov.ua/en/news/11868.html"class="root_r"> Administrative and Territorial Division</a>
        
    </li>  
    
     <li  class="last">         
    
                        
         <a href="#"  class="root">News</a>         


    <div class="submenu">  


        <div class="submenu_col">

        <h3><a href="http://portal.rada.gov.ua/rada/control/en/index">Last news</a></h3>   

        <ul>

        <li><a href=" http://iportal.rada.gov.ua/en/news">News</a></li>
        <li><a href="/en/preview/upc_tvents">Upcoming events</a></li>
        <li><a href="http://iportal.rada.gov.ua/en/news/News/Plenary_meetings">Plenary Meetings</a></li>
        <li><a href="http://iportal.rada.gov.ua/en/news/top_news">Top News</a></li>
        {*<li><a href="http://portal.rada.gov.ua/rada/control/en/publish/category/info_left?cat_id=106064">Parliamentary Calendar of Important and Memorable Dates</a></li>*}
        </ul>       
                 

        </div>
        
        
        </li>  
          

    {* <li >


    <a href="#"  class="root">Інформація</a>            


    <div class="submenu">      



        <div class="submenu_col">

        <h3>Оперативна інформація</h3>     

        <ul>

            <li><a href="http://w1.c1.rada.gov.ua/pls/zweb_n/doclist1?what=1">Укази та розпорядження Президента України</a></li>

            <li><a href="http://w1.c1.rada.gov.ua/pls/zweb_n/doclist1?what=0">Постанови та розпорядження КМ України</a></li>  
                   </ul>   

        </div>

        <div class="submenu_col">

        <h3>Довідкова інформація</h3>   

        <ul>

            <li><a href="/news/Novyny/Derzhavni_zakupivli/">Державні закупівлі</a></li>

            <li><a href="http://w1.c1.rada.gov.ua/pls/wph/webph_s">Довідник телефонів Верховної Ради України</a></li>

            <li><a href="/news/Novyny/Parlamentskyj_dovidnyk_znamennykh_i_pamyatnykh_dat/">Довідник знаменних і пам'ятних дат ВР України</a></li>

            <li><a href="http://dovidka.com.ua/">Довідник "Офіційна Україна сьогодні"</a></li>

            <li><a href="#">Правила користування веб-сайтом</a></li>

            <li><a href="#">Допомога щодо користування веб-сайтом</a></li>
        </ul>   

        </div>

        <div class="submenu_col">

        <h3>Запити на інформацію</h3>   

        <p>Доівдки з питань доступу до публічної інформації</p>                                            
        <ul>

            <li><a href="/documents/dostpubinfo/45915.html">Документи якими керується Апарат ВР України у питаннях доступу до публічної інформації</a></li>

            <li><a href="/documents/dostpubinfo/45916.html">Види інформації, якою володіє Апарат ВР України</a></li>

            <li><a href="/news/Zapyty_na_informatsiyu/Zvity/">Звіти</a></li>
        </ul>     

        <p>Форми доступу до публічної інформації</p>                                            
        <ul>

            <li><a href="http://w1.c1.rada.gov.ua/pls/site/pkg_public_info.request_form">Електронна форма запиту</a></li>

            <li><a href="#">Паперова форма запиту</a></li>   
                    </ul>
                           

        </div>   

    </div> 

    </li>   
    
    <li >     

    <a href="#"  class="root">Контакти</a>            

    <div class="submenu">    


        <div class="submenu_col">

        <h3>Зворотний зв'язок</h3>


        <ul>

            <li><a href="feedback">Форма зворотнього зв'язку</a></li>

            <li><a href="/feedback">Адреса Верховної Ради України</a></li>
        </ul>



        </div>
        
        <div class="submenu_col">

        <h3>Запити громадян</h3>


        <ul>

            <li><a href="http://vzvernen.rada.gov.ua/vzvernen/control/uk/index">Відділ з питань звернень громадян</a></li>

        </ul>



        </div>
        
        
        
        

<div class="submenu_col">

    <h3>Обслуговування ЗКТ</h3>


        <ul>

            <li><a href="http://lapp.rada.gov.ua/request/">Електронна форма заявки</a></li>

            
        </ul>



        </div>
        

    </div>




    </li>


    <li >


    <a href="#"  class="root">Ресурси</a>            


    <div class="submenu">





        <div class="submenu_col">

        <h3>Україна. Адмін.тер.устрій</h3>




        <ul>

            <li><a href="http://w1.c1.rada.gov.ua/pls/z7502/a002">Статистика</a></li>

            <li><a href="http://w1.c1.rada.gov.ua/pls/z7502/zv.cf1">Пошук за реквізитами</a></li>
        </ul>
        
        <p>
            Довідники
        </p>
        <ul>

            <li><a href="http://static.rada.gov.ua/zakon/new/NEWSAIT/ADM/zmist.html">Адміністративно-територіальний устрій</a></li>

            <li><a href="http://static.rada.gov.ua/site/ukr/atuu/dovidnyk/20110617_tel_dovidnyk_rad.pdf">Телефони керівників місцевих рад</a></li>
        <li><a href="http://static.rada.gov.ua/zakon/new/NEWSAIT/ADM/dov/zmist.html">Довідник телефонів та поштових адрес Верховної Ради Автономної Республіки Крим та місцевих рад</a></li>
        
        </ul>
        
        <p> Нормативно-правові акти з питань адміністративно-територіального устрою України</p>
        <ul>
            <li><a href="http://w1.c1.rada.gov.ua/pls/z7502/A035?rdat=30.06.2004&letter=0">Пошук по областях</a></li>
            <li><a href="http://w1.c1.rada.gov.ua/pls/z7502/a034">Пошук по роках</a></li>
         </ul>
        <P>
            Місцеві вибори
        </P>
<ul>
            <li><a href="http://iportal.rada.gov.ua/fsview/46076.html">Місцеві вибори 2010</a></li>
            <li><a href="http://iportal.rada.gov.ua/fsview/46086.html">Позачергові місцеві вибори</a></li>
        </ul>

        </div>
        
        <div class="submenu_col">

        <h3><a href="#">Інформаційні ресурси</a></h3>
        <P>
            Інформаційні ресурси Верховної Ради України
        </P>
        <ul>
                   <li><a href="http://w1.c1.rada.gov.ua/pls/site/p_komitis_site">Веб-сайти комітетів Верховної Ради України</a></li>
        <li><a href="http://bilshist.rada.gov.ua/">Сайт парламентської більшості у Верховній Раді України шостого скликання</a></li>
        <li><a href="http://lib.rada.gov.ua/">Бібліотечно-бібліографічні ресурси</a></li>
        <li><a href="{$site_domain}/documents">Електронний архів документів</a></li>
        <li><a href="http://instzak.rada.gov.ua/">Інститут законодавства Верховної Ради України</a></li>
    <li><a href="http://euinfocentre.rada.gov.ua">Європейський центр інформаційної підтримки Верховної Ради України</a>
    </li>
    <li><a href="http://www.rada.gov.ua/~dtrp/">Дирекція телерадіопрограм Верховної Ради України </a></li>
        </ul>
        
        <p>
            Зовнішні інформаційні ресурси
        </p>
        <ul>
                 
                 <li><a href="http://www.golos.com.ua/">Газета Верховної Ради "Голос України"</a></li>
                 <li><a href="http://www.viche.info/">Журнал "Віче"</a></li>
                 <li><a href="http://www.nardep.com/">Депутатський клуб "Парламент" та журнал "Народний депутат"</a></li>
            </ul>
        </div>
        
        <div class="submenu_col">

        <h3><a href="#">Веб-сайти органів держ. влади</a></h3>
        
        <ul>
            <li><a href="http://www.president.gov.ua/">Президент України</a></li>
          </ul>
        <p>
            Виконавча влада
            </p>
            <ul>   
            <li><a href="http://www.kmu.gov.ua/">Кабінет Міністрів України</a></li>
            </ul>
        
        <P>
            Судова влада
        </P>
        <ul>
                <li><a href="http://www.scourt.gov.ua/">Верховний Суд України</a></li>
                <li><a href="http://www.ccu.gov.ua/">Конституційний Суд України</a></li>
                <li><a href="http://www.arbitr.gov.ua/">Вищий господарський суд України</a></li>
            </ul>
        <P>
            Інші державні органи
        </P>
        <ul>
                <li><a href="http://www.cvk.gov.ua/">Центральна виборча комісія України</a></li>
        <li><a href="http://www.rainbow.gov.ua/">Рада національної безпеки і оборони України</a></li>
        <li><a href="http://www.ombudsman.kiev.ua/">Уповноважений з прав людини</a></li>
        <li><a href="http://www.ac-rada.gov.ua/">Рахункова палата України</a></li>
            </ul>
        
        </div>




    </li>  *}


   {*  <li  class="last">  


      <a href="#"  class="root">Новини</a>            


    <div class="submenu">





        <div class="submenu_col">

        <h3><a href="#">Оперативні новини</a></h3>




        <ul>

            <li><a href="/news/Novyny/Povidomlennya/">Повідомлення  </a></li>

            <li><a href="/preview/Anonsy_podij/">Анонси подій</a></li>

            <li><a href="/news/Novyny/Plenarni_zasidannya/">Пленарні засідання</a></li>

            <li><a href="/news/Novyny/Parlamentski_slukhannya/">Парламентські слухання</a></li>

            <li><a href="/news/Novyny/Dni_Uryadu/">Дні Уряду</a></li>
        </ul>





        </div>

        <div class="submenu_col">

        <h3>Огляди ЗМІ</h3>




        <ul>

            <li><a href="http://portal.rada.gov.ua/rada/control/uk/archive/docview?typeId=108345">ЗМІ про парламент</a></li>

            <li><a href="http://lib.rada.gov.ua/static/LIBRARY/monitor/degist-region.htm">Огляд регіональної преси</a></li>

            <li><a href="http://iportal.rada.gov.ua/documents/Oglad_reg_ZMIvf/49243.html">Архів оглядів регіональної преси</a></li>

            <li><a href="/documents/Parlam_visti/">Парламентські вісті</a></li>
        </ul>





        </div>

        <div class="submenu_col">

        <h3>Мультимедіа</h3>




        <ul>

            <li><a href="/gallery/">Фото</a></li>

            <li><a href="/video/">Відео</a></li>

            <li><a href="/audio/">Аудіо</a></li>
        </ul>





        </div>  


    </div>    

    </li>  *}
    
    
    
</ul>
<!-- cut TOP MENU--> 