<!--TOP MENU cut -->
<ul id="topnav" class="lbut">
	<li><a href="{$site_domain}">Головна</a></li>
	<li><a href="{$site_domain}/documents/dostpubinfo/45915.html">Доступ до публічної інформації</a></li>
	<li><a href="http://w1.c1.rada.gov.ua/pls/site2/pkg_public_info.request_form">Електронна форма запиту</a></li>
	<li><a href="{$site_domain}/documents/dostpubinfo/45916.html">Види інформації</a></li>
	<li><a href="{$site_domain}/news/Zapyty_na_informatsiyu/Zvity">Звіти</a></li>
	
	<li><a href="#">Контакти</a>
		<div class="sub">

		<ul>
			<li><h3><a href="{$site_domain}/feedback">Зворотний зв'язок</a></h3></li>

			<!--<li><a href="{$site_domain}/infocenter">Віртуальна приймальня</a></li>-->
			<li><a href="http://vzvernen.rada.gov.ua/vzvernen/control/uk/index">Відділ з питань звернень громадян</a></li>
			<li><a href="{$site_domain}/news/Poryadok_akredytatsiji,_Polozhennya_pro_ekskursiji">Порядок акредитації, Положення про екскурсії</a></li>
			<!-- <li><a href="">Контактна інформація</a></li>-->
			<li><a href="#">Адреса Верховної Ради України</a></li>
			<!--http://w1.c1.rada.gov.ua/pls/site2/el_main.vr_address-->
		</ul>

		</div>
	</li>
</ul>
<!-- cut TOP MENU-->