<!--TOP MENU cut -->
<ul id="topnav" class="lbut">
<li><a href="{$site_domain}">Головна</a></li>

<li><a href="#">Склад і структура</a>
	<div class="sub">
		<ul>
			<li><a href="http://w1.c1.rada.gov.ua/pls/site2/p_head_vru">Голова Верховної Ради України</a></li>
			<li><a href="http://w1.c1.rada.gov.ua/pls/site2/p_kerivnyky_vru">Керівництво Верховної Ради України</a></li>
			<li><a href="http://w1.c1.rada.gov.ua/pls/site2/p_deputat_list">Народні депутати України</a></li>
			<li><a href="http://w1.c1.rada.gov.ua/pls/site2/p_fractions">Депутатські фракції</a></li>
			<li><a href="http://w1.c1.rada.gov.ua/pls/site2/p_komitis">Комітети Верховної Ради України</a></li>
			<li><a href="http://w1.c1.rada.gov.ua/pls/site2/p_temp_komitis">Тимчасові комісії</a></li>
			<li><a href="http://w1.c1.rada.gov.ua/pls/site2/p_aparat">Апарат</a></li>
		</ul>
	</div>
</li>

<li><a href="#">Парламентаризм в Україні</a>
    <div class="sub">
    <ul>
		<li><a href="{$site_domain}/documents/parliamentarism/45945.html">Становлення української державності</a></li>
        <li><a href="http://static.rada.gov.ua/site/const/index.html">Конституційний процес в Україні</a></li>
        <li><a href="#">Державна символіка</a></li>

    </ul>

    </div>
</li>

<li><a href="#">Попередні скликання</a>
    <div class="sub">
    <ul>
        <li><a href="http://static.rada.gov.ua/zakon/new/NEWSAIT/DEPUTAT1/spisok1.htm">1 скликання (1990-1994)</a></li>
        <li><a href="http://w1.c1.rada.gov.ua/pls/radac_gs09/d_index_arh?skl=2">2 скликання (1994-1998)</a></li>

        <li><a href="#">3 скликання (1998-2002)</a><ul>

            <li><a href="http://w1.c1.rada.gov.ua/pls/radac_gs09/d_index_arh?skl=3">Народні депутати</a></li>
            <li><a href="http://w1.c1.rada.gov.ua/pls/radac_gs09/h_index_arh?nom_skl=3">Хронологія розгляду</a></li>
        </ul></li>
        <li><a href="#">4 скликання (2002-2006)</a><ul>
            <li><a href="http://w1.c1.rada.gov.ua/pls/site2/p_head_vru">Народні депутати</a></li>
            <li><a href="http://w1.c1.rada.gov.ua/pls/radac_gs09/h_index_arh?nom_skl=4">Хронологія розгляду</a></li>

        </ul></li>
        <li><a href="#">5 скликання (2006-2007)</a><ul>
            <li><a href="http://w1.c1.rada.gov.ua/pls/site2/p_deputat_list?skl=6">Народні депутати</a></li>
            <li><a href="http://w1.c1.rada.gov.ua/pls/radac_gs09/h_index_arh?nom_skl=5">Хронологія розгляду</a></li>
            <li><a href="{$site_domain}/documents/parliamentarism/45949.html">Правова база діяльності</a></li>
        </ul></li>
    </ul>

    </div>
</li>

	<li><a href="#">Контакти</a>
		<div class="sub">

		<ul>
			<li><h3><a href="{$site_domain}/feedback">Зворотний зв'язок</a></h3></li>

			<!--<li><a href="{$site_domain}/infocenter">Віртуальна приймальня</a></li>-->
			<li><a href="http://vzvernen.rada.gov.ua/vzvernen/control/uk/index">Відділ з питань звернень громадян</a></li>
			<li><a href="{$site_domain}/news/Poryadok_akredytatsiji,_Polozhennya_pro_ekskursiji">Порядок акредитації, Положення про екскурсії</a></li>
			<!-- <li><a href="">Контактна інформація</a></li>-->
			<li><a href="#">Адреса Верховної Ради України</a></li>
			<!--http://w1.c1.rada.gov.ua/pls/site2/el_main.vr_address-->
		</ul>

		</div>
	</li>

</ul>
<!-- cut TOP MENU-->