<!--TOP MENU cut -->
<ul id="topnav" class="lbut">

    <li><a href="{$site_domain}">Головна</a></li>

    <li><a href="#">Нормативно-правова база України</a>
        <div class="sub left">

            <ul>
                <li><h3><a href="http://zakon2.rada.gov.ua/laws/"></a>Законодавство України</a></h3></li>
                <li><a href="http://zakon2.rada.gov.ua/laws/main/a#Find">Пошук за реквізитами</a></li>
                <li><a href="http://zakon2.rada.gov.ua/laws/main/nn">Надходження законодавства</a></li>
                <li><a href="http://zakon2.rada.gov.ua/laws/main/a/stru2">Структура бази даних</a></li>
                <li><a href="http://zakon2.rada.gov.ua/laws/main/c">Міжнародні документи</a></li>
                <li><a href="http://zakon2.rada.gov.ua/laws/main/d">Популярні документи</a></li>
                <li><a href="http://zakon2.rada.gov.ua/laws/main/perv">Первинні законодавчі акти</a></li>
                <li><a href="http://zakon2.rada.gov.ua/laws/main/koms">Розподіл за комітетами ВР</a></li>
                <li><a href="http://zakon2.rada.gov.ua/laws/main/annot">Анотації англійською мовою</a></li>
                <li><a href="http://zakon2.rada.gov.ua/laws/main/termin">Термінологія законодавства</a></li>
            </ul>
            <ul>
                <li><h3>Законодавство АР Крим</h3></li>
                <li><a href="http://zakon2.rada.gov.ua/krym/main/a#Find">Пошук за реквізитами</a></li>
                <li><a href="http://zakon2.rada.gov.ua/krym/main/a/stru2">Структура бази даних</a></li>
            </ul>

        </div>
    </li>
    <li><a href="#">Правова база діяльності Верховної Ради України</a>
        <div class="sub">
            <ul>
                <li><a href="http://zakon2.rada.gov.ua/laws/show/254%EA/96-%E2%F0">Конституція України</a></li>
                <li><a href="http://zakon2.rada.gov.ua/laws/show/1861-17">Закон України "Про Регламент Верховної Ради України"</a></li>
                <li><a href="http://zakon2.rada.gov.ua/laws/show/2790-12">Закон України "Про статус народного депутата України"</a></li>
                <li><a href="http://zakon2.rada.gov.ua/rada/show/116/95-%E2%F0">Закон України "Про комітети Верховної Ради України"</a></li>
                <li><a href="http://zakon2.rada.gov.ua/rada/show/116/95-%E2%F0">Положення про Апарат Верховної Ради України</a></li>
            </ul>
        </div>
    </li>
</ul>